/**
 * OPHERIX — Plataforma SaaS de gestión de personal para eventos
 * © 2026 Cristhian Paul Prestán. Todos los derechos reservados.
 * Propiedad intelectual exclusiva del autor. Prohibida su reproducción,
 * distribución o uso no autorizado, total o parcial, sin consentimiento
 * expreso por escrito del autor.
 */

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Nota: la config de Prisma 7 (@prisma/config) aún no soporta un campo
    // `directUrl` separado — solo `url` (y `shadowDatabaseUrl`). Para Neon,
    // usar la connection string "pooled" también para migraciones funciona
    // en la práctica; DIRECT_URL queda documentada en .env.example por si
    // una versión futura de Prisma lo soporta.
    url: process.env["DATABASE_URL"],
  },
});
